package com.neon.api;

import com.neon.api.data.model.Room;
import com.neon.api.data.repository.RoomRepository;
import com.neon.api.data.services.SequenceGeneratorService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

// TODO: spring session / auth  ... ?
// TODO: create room (thread safe) => room UID + PIN ?
// TODO: JOIN session (thread safe)

// TODO: Estimate

@RestController
public class ApiController {

    @Autowired // get the bean, which is auto-generated by Spring
    private RoomRepository roomRepository;

    @Autowired
    private SequenceGeneratorService sequenceGeneratorService;


    @GetMapping("/room")
    public Room getRoom(@RequestParam(value = "id", defaultValue = "-1") long id) {
        return roomRepository.findById(id).get();
    }

    @PostMapping("/room")
    public Room createRoom(@RequestParam(value = "description", defaultValue = "Room description", required = false) String description) {
        var room = new Room(description);
        roomRepository.save(room);
        return room;
    }
}
